project: "Object_Classification_&_Detection"
hardware: "Red_Pitaya_FIUS"

dataset:
  input_size: 2048
  # Increased samples_per_file to reflect your high-density data collection
  samples_per_file: 400
  # Ensure the order matches the Class Weights in train.py exactly
  classes: ["Wall", "Person", "Chair", "Backpack", "Plant", "BigTable"]
  use_dummy: false 
  # NEW: Add a normalization flag to make the pipeline clear
  normalization: "max_abs" 

paths:
  raw_dir: "./data/raw/"
  processed_dir: "./data/processed/"
  model_output: "./models/fius_cnn_v1.pth"

training:
  batch_size: 16       # DECREASED: Better for learning complex features like human echoes
  epochs: 150          # INCREASED: Gives the model more time to adjust to Class Weights
  learning_rate: 0.001   # <--- Change this from 0.0005
  weight_decay: 0.00005  # <--- Halved this to let the model explore more